apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: python-component-sample
  annotations:
    build.appstudio.openshift.io/request: "configure-pac"
    image.redhat.com/generate: '{"visibility": "public"}'
spec:
  componentName: python-sample-component-name
  application: application-sample
  source:
    git:
      url: https://github.com/mmorhun/sample-multi-component
      context: python-component
